development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: duffynyap_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: duffynyap_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: duffynyap_production
  pool: 5
  username: root
  password:
